/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import logica.VentanillaL;

public class VentanillaVisual extends javax.swing.JFrame {

    private VentanillaL ventanilla1 = new VentanillaL();
    private VentanillaL ventanilla2 = new VentanillaL();
    private VentanillaL ventanilla3 = new VentanillaL();
    private static JLabel[] asientosLabels;
    /**
     * Creates new form VentanillaVisual
     */
    public VentanillaVisual() {
        initComponents();
        ventanilla1.setNumVentanilla("1");
        ventanilla2.setNumVentanilla("2");
        ventanilla3.setNumVentanilla("3");
        VentanillaL.inicializarAsientos();
        VentanillaL.setTextArea(txtresp1);
        ventanilla1.start();
        ventanilla2.start();
        ventanilla3.start();

        crearAsientosAvion();
    }
    
        public void crearAsientosAvion() {

        /*for (int i = 0; i < VentanillaL.getNUM_ASIENTOS(); i++) {
        JLabel label = new JLabel("Asiento " + (i+1));
        label.setBackground(Color.GREEN);
        label.setOpaque(true);
        jPanelAvion.add(label);
        }*/
        asientosLabels = new JLabel[VentanillaL.getNUM_ASIENTOS()];
        for (int i = 0; i < VentanillaL.getNUM_ASIENTOS(); i++) {
            asientosLabels[i] = new JLabel("Asiento " + (i + 1));
            asientosLabels[i].setBackground(Color.GREEN);
            asientosLabels[i].setOpaque(true);
            asientosLabels[i].setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(Color.BLACK),
                    BorderFactory.createEmptyBorder(7, 10, 7, 10)
            ));
            asientosLabels[i].setFont(asientosLabels[i].getFont().deriveFont(12.0f));
        }
        for (int i = 0; i < VentanillaL.getNUM_ASIENTOS(); i++) {
            jPanelAvion.add(asientosLabels[i]);
        }

        VentanillaL.setAsientosLabels(asientosLabels);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAvion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtresp1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtAsientoV1 = new javax.swing.JTextField();
        txtClienteV1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxV1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtcambAV1 = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btncambiar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtAsientoV2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtClienteV2 = new javax.swing.JTextField();
        cbxV2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtcambAV2 = new javax.swing.JTextField();
        btnguardar1 = new javax.swing.JButton();
        btncambiar2 = new javax.swing.JButton();
        btneliminar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnguardar2 = new javax.swing.JButton();
        btneliminar2 = new javax.swing.JButton();
        btncambiar3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtClienteV3 = new javax.swing.JTextField();
        txtAsientoV3 = new javax.swing.JTextField();
        cbxV3 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtcambAV3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aerolinea Software");

        jPanelAvion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAvion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtresp1.setColumns(20);
        txtresp1.setRows(5);
        jScrollPane2.setViewportView(txtresp1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventanilla 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel4.setText("Nº asiento:");

        jLabel5.setText("Cédula cliente:");

        cbxV1.setText("Cambiar");
        cbxV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxV1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nuevo Asiento:");

        txtcambAV1.setEnabled(false);

        btnguardar.setText("Reservar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncambiar.setText("Cambiar");
        btncambiar.setEnabled(false);
        btncambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambiarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("------------------Cambiar Asiento---------------------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnguardar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel3)))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btncambiar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btneliminar))
                                    .addComponent(txtcambAV1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbxV1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAsientoV1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(txtClienteV1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsientoV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClienteV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcambAV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btncambiar)
                    .addComponent(btneliminar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventanilla 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel7.setText("Nº asiento:");

        jLabel8.setText("Cédula cliente:");

        cbxV2.setText("Cambiar");
        cbxV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxV2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nuevo Asiento:");

        txtcambAV2.setEnabled(false);

        btnguardar1.setText("Reservar");
        btnguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar1ActionPerformed(evt);
            }
        });

        btncambiar2.setText("Cambiar");
        btncambiar2.setEnabled(false);
        btncambiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambiar2ActionPerformed(evt);
            }
        });

        btneliminar1.setText("Eliminar");
        btneliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar1ActionPerformed(evt);
            }
        });

        jLabel13.setText("------------------Cambiar Asiento---------------------");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(btnguardar1)
                .addGap(18, 18, 18)
                .addComponent(btncambiar2)
                .addGap(18, 18, 18)
                .addComponent(btneliminar1)
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtcambAV2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxV2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(40, 40, 40)
                                .addComponent(txtAsientoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtClienteV2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAsientoV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtClienteV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxV2)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcambAV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar1)
                    .addComponent(btncambiar2)
                    .addComponent(btneliminar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jLabel13)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventanilla 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnguardar2.setText("Reservar");
        btnguardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar2ActionPerformed(evt);
            }
        });

        btneliminar2.setText("Eliminar");
        btneliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar2ActionPerformed(evt);
            }
        });

        btncambiar3.setText("Cambiar");
        btncambiar3.setEnabled(false);
        btncambiar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambiar3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Nº asiento:");

        jLabel10.setText("Cédula cliente:");

        cbxV3.setText("Cambiar");
        cbxV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxV3ActionPerformed(evt);
            }
        });

        jLabel11.setText("Nuevo Asiento:");

        txtcambAV3.setEnabled(false);

        jLabel12.setText("------------------Cambiar Asiento---------------------");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(cbxV3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnguardar2)
                                        .addGap(17, 17, 17)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btncambiar3)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar2))
                            .addComponent(txtcambAV3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAsientoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClienteV3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsientoV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtClienteV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxV3)
                .addGap(2, 2, 2)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcambAV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar2)
                    .addComponent(btncambiar3)
                    .addComponent(btneliminar2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanelAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jPanelAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxV2ActionPerformed
        if (cbxV2.isSelected()) {
            btncambiar2.setEnabled(true);
            txtcambAV2.setEnabled(true);
        } else {
            btncambiar2.setEnabled(false);
            txtcambAV2.setEnabled(false);
            txtcambAV2.setText("");
        }
    }//GEN-LAST:event_cbxV2ActionPerformed

    private void cbxV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxV3ActionPerformed
        if (cbxV3.isSelected()) {
            btncambiar3.setEnabled(true);
            txtcambAV3.setEnabled(true);
        } else {
            btncambiar3.setEnabled(false);
            txtcambAV3.setEnabled(false);
            txtcambAV3.setText("");
        }
    }//GEN-LAST:event_cbxV3ActionPerformed
        private volatile boolean esperandoCambioAsiento = false;
    private void btnguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar1ActionPerformed
        int asiento = Integer.parseInt(txtAsientoV2.getText());
        String cliente = txtClienteV2.getText();
        if (!ventanilla2.isAlive()) {
            ventanilla2 = new VentanillaL();
            ventanilla2.setNumVentanilla("2");
            ventanilla2.start();
        }
        ventanilla2.setNombreCliente(cliente);
        ventanilla2.setNumeroAsiento(asiento);
        ventanilla2.setInicio(true);
        ventanilla2.setAccion("reservar");
    }//GEN-LAST:event_btnguardar1ActionPerformed

    private void btncambiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambiar2ActionPerformed
        int Asiento = Integer.parseInt(txtAsientoV2.getText());
        int NuevoAsiento = Integer.parseInt(txtcambAV2.getText());
        String Cliente = txtClienteV2.getText();
        ventanilla2 = new VentanillaL(); 
        ventanilla2.setNumVentanilla("2");
        ventanilla2.start();
        ventanilla2.setInicio(true);
        ventanilla2.setNombreCliente(Cliente);
        ventanilla2.setNumeroAsiento(NuevoAsiento);
        ventanilla2.setLastAsiento(Asiento);
        ventanilla2.setAccion("cambiar");
    }//GEN-LAST:event_btncambiar2ActionPerformed

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed
        int Asiento = Integer.parseInt(txtAsientoV2.getText());
        String Cliente = txtClienteV2.getText();
        ventanilla2.setNombreCliente(Cliente);
        ventanilla2.setNumeroAsiento(Asiento);
        try {
            ventanilla2.eliminarReserva();
        } catch (InterruptedException ex) {
            Logger.getLogger(VentanillaVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneliminar1ActionPerformed

    private void btnguardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar2ActionPerformed
        int asiento = Integer.parseInt(txtAsientoV3.getText());
        String cliente = txtClienteV3.getText();
        if (!ventanilla3.isAlive()) {
            ventanilla3 = new VentanillaL();
            ventanilla3.setNumVentanilla("3");
            ventanilla3.start();
        }
        ventanilla3.setNombreCliente(cliente);
        ventanilla3.setNumeroAsiento(asiento);
        ventanilla3.setInicio(true);
        ventanilla3.setAccion("reservar");
    }//GEN-LAST:event_btnguardar2ActionPerformed

    private void btncambiar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambiar3ActionPerformed
        int Asiento = Integer.parseInt(txtAsientoV3.getText());
        int NuevoAsiento = Integer.parseInt(txtcambAV3.getText());
        String Cliente = txtClienteV3.getText();
        ventanilla3 = new VentanillaL(); 
        ventanilla3.setNumVentanilla("3");
        ventanilla3.start();
        ventanilla3.setInicio(true);
        ventanilla3.setNombreCliente(Cliente);
        ventanilla3.setNumeroAsiento(NuevoAsiento);
        ventanilla3.setLastAsiento(Asiento);
        ventanilla3.setAccion("cambiar");
    }//GEN-LAST:event_btncambiar3ActionPerformed

    private void btneliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar2ActionPerformed
        int Asiento = Integer.parseInt(txtAsientoV3.getText());
        String Cliente = txtClienteV3.getText();
        ventanilla3.setNombreCliente(Cliente);
        ventanilla3.setNumeroAsiento(Asiento);
        try {
            ventanilla3.eliminarReserva();
        } catch (InterruptedException ex) {
            Logger.getLogger(VentanillaVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneliminar2ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int Asiento = Integer.parseInt(txtAsientoV1.getText());
        String Cliente = txtcambAV1.getText();
        ventanilla1.setNombreCliente(Cliente);
        ventanilla1.setNumeroAsiento(Asiento);
        try {
            ventanilla1.eliminarReserva();
            //txtresp1.setText(ventanilla1.getMensaje());
        } catch (InterruptedException ex) {
            Logger.getLogger(VentanillaVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambiarActionPerformed
        int Asiento = Integer.parseInt(txtAsientoV1.getText());
        int NuevoAsiento = Integer.parseInt(txtcambAV1.getText());
        String Cliente = txtClienteV1.getText();
        ventanilla1 = new VentanillaL();
        ventanilla1.setNumVentanilla("1");
        ventanilla1.start();
        ventanilla1.setInicio(true);
        ventanilla1.setNombreCliente(Cliente);
        ventanilla1.setNumeroAsiento(NuevoAsiento);
        ventanilla1.setLastAsiento(Asiento);
        ventanilla1.setAccion("cambiar");
    }//GEN-LAST:event_btncambiarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        int asiento = Integer.parseInt(txtAsientoV1.getText());
        String cliente = txtClienteV1.getText();
        if (!ventanilla1.isAlive()) {
            ventanilla1 = new VentanillaL();
            ventanilla1.setNumVentanilla("1");
            ventanilla1.start();
        }
        ventanilla1.setNombreCliente(cliente);
        ventanilla1.setNumeroAsiento(asiento);
        ventanilla1.setInicio(true);
        ventanilla1.setAccion("reservar");
    }//GEN-LAST:event_btnguardarActionPerformed

    private void cbxV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxV1ActionPerformed
        if (cbxV1.isSelected()) {
            btncambiar.setEnabled(true);
            txtcambAV1.setEnabled(true);
        } else {
            btncambiar.setEnabled(false);
            txtcambAV1.setEnabled(false);
            txtcambAV1.setText("");
        }
    }//GEN-LAST:event_cbxV1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanillaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanillaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanillaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanillaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanillaVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncambiar;
    private javax.swing.JButton btncambiar2;
    private javax.swing.JButton btncambiar3;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton btneliminar2;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnguardar1;
    private javax.swing.JButton btnguardar2;
    private javax.swing.JCheckBox cbxV1;
    private javax.swing.JCheckBox cbxV2;
    private javax.swing.JCheckBox cbxV3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelAvion;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAsientoV1;
    private javax.swing.JTextField txtAsientoV2;
    private javax.swing.JTextField txtAsientoV3;
    private javax.swing.JTextField txtClienteV1;
    private javax.swing.JTextField txtClienteV2;
    private javax.swing.JTextField txtClienteV3;
    private javax.swing.JTextField txtcambAV1;
    private javax.swing.JTextField txtcambAV2;
    private javax.swing.JTextField txtcambAV3;
    private static javax.swing.JTextArea txtresp1;
    // End of variables declaration//GEN-END:variables
}
